defmodule SkillBridgeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :skill_bridge

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_skill_bridge_key",
    signing_salt: "mF2TQ9zB",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", SkillBridgeWeb.UserSocket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Serve user-uploaded profile images — never gzip, never digest,
  # always fresh (uploads change at runtime, unlike compiled assets).
  plug Plug.Static,
    at: "/uploads",
    from: {:skill_bridge, "priv/static/uploads"},
    gzip: false,
    headers: %{"cache-control" => "public, max-age=31536000"}

  # Serve compiled static assets (JS, CSS, fonts, images)
  plug Plug.Static,
    at: "/",
    from: :skill_bridge,
    gzip: not code_reloading?,
    only: SkillBridgeWeb.static_paths() -- ["uploads"],
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :skill_bridge
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SkillBridgeWeb.Router
end
