import Config

# Configure your database
config :skill_bridge, SkillBridge.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "skill_bridge_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :skill_bridge, SkillBridgeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "mCgDKJIEB6rLGth9w7TV4nc0bSJY/xwTmj/RgE/J4i9G9Uunv48Bq+mwmOvyMokE",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:skill_bridge, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:skill_bridge, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :skill_bridge, SkillBridgeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/skill_bridge_web/router\.ex$"E,
      ~r"lib/skill_bridge_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :skill_bridge, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Use simulated card payments locally unless STRIPE_SECRET_KEY is set
payments_mode =
  if System.get_env("STRIPE_SECRET_KEY") in [nil, ""], do: :simulated, else: :stripe

config :skill_bridge, :payments, mode: payments_mode

config :skill_bridge, :stripe,
  secret_key: System.get_env("STRIPE_SECRET_KEY"),
  webhook_secret: System.get_env("STRIPE_WEBHOOK_SECRET"),
  publishable_key: System.get_env("STRIPE_PUBLISHABLE_KEY"),
  currency: System.get_env("STRIPE_CURRENCY", "pkr")

# Supabase OAuth (Google sign-in)
# Set SUPABASE_URL and SUPABASE_ANON_KEY in your environment before starting the server
config :skill_bridge, :supabase,
  url: System.get_env("SUPABASE_URL", ""),
  anon_key: System.get_env("SUPABASE_ANON_KEY", "")
